### ISSUE TITLE
0.5.0 release failed

### ISSUE THREAD

**Issue by anguslees** [bazel-contrib/bazel-mypy-integration#79]
I see a `0.5.0` tag, and some comments on other bugs that look like it was intended to be a release.  The recent changes to publish a release artefact look to have failed, or at least didn't work for 0.5.0; there are no 'notes' anywhere; and github thinks the most recent release is 0.4.0.

**Comment by mrtnkb** [comment]
Hi,

I'm also interested in using a recent version of bazel-mypy-integration with a recent version of MyPy but I'm running into what I think are the same issues (see below for reference).

Is there a way to support getting a fixed release cut? I'd be happy to tackle some PRs or testing if help would be welcome.

Currently required workarounds, for reference:
- Additional import of buildifier_prebuilt external repository is required
- Need to define a mypy_integration_pip_deps external repo with pip_parse (plus additional package requirements)
- mypy 0.981 or greater isn't supported due to changed function signature

**Comment by EricWiener** [comment]
Hi @mrtnkb, is there any chance you could provide a reference for what the correct `WORKSPACE` looks like with your workarounds applied?

**Comment by mrtnkb** [comment]
> 

Unfortunately I don't have the diff anymore

**Comment by alexeagle** [comment]
Hey all, sorry that release never got fixed, I have fresh effort to apply here and am re-writing it in https://github.com/aspect-build/rules_lint/issues/79
